version: '3.8'

# The default docker-compose.override file can use the "localhost" as the external name for testing web apps within the same dev machine.
# The EPROCESSOR_EXTERNAL_DNS_NAME_OR_IP environment variable is taken, by default, from the ".env" file defined like:
#     EPROCESSOR_EXTERNAL_DNS_NAME_OR_IP=localhost
# but values present in the environment vars at runtime will always override those defined inside the .env file

services:
  maildev:
    ports:
      - '5500:1080'
      - '1025:1025'

  rabbitmq:
    ports:
      - '5672:5672'

  redis:
    image: redis:alpine
    ports:
      - '5379:6379'

  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - '5340:80'

  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - '5433:1433'
    volumes:
      - eprocessor-sqldata:/var/opt/mssql

  zipkin:
    ports:
      - '5411:9411'

  todo-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - SeqServerUrl=http://seq
    ports:
      - '5154:80'
      - '50155:50154'

  todo-api-dapr:
    command:
      [
        './daprd',
        '-app-id',
        'todo-api',
        '-app-port',
        '80',
        '-components-path',
        '/components',
        '-config',
        '/configuration/eprocessor-config.yaml',
      ]
    volumes:
      - './dapr/components/:/components'
      - './dapr/configuration/:/configuration'

  fake-fetch-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RetryMigrations=true
      - SeqServerUrl=http://seq
    ports:
      - '5101:80'
      - '50002:50001'

  fake-fetch-api-dapr:
    command:
      [
        './daprd',
        '-app-id',
        'fake-fetch-api',
        '-app-port',
        '80',
        '-components-path',
        '/components',
        '-config',
        '/configuration/eprocessor-config.yaml',
      ]
    volumes:
      - './dapr/components/:/components'
      - './dapr/configuration/:/configuration'

  fake-fetch-ca-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - SeqServerUrl=http://seq
    ports:
      - '5158:80'
      - '50159:50158'

  fake-fetch-ca-api-dapr:
    command:
      [
        './daprd',
        '-app-id',
        'fake-fetch-ca-api',
        '-app-port',
        '80',
        '-components-path',
        '/components',
        '-config',
        '/configuration/eprocessor-config.yaml',
      ]
    volumes:
      - './dapr/components/:/components'
      - './dapr/configuration/:/configuration'

  fetch-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - SeqServerUrl=http://seq
    ports:
      - '5153:80'
      - '50153:50152'

  fetch-api-dapr:
    command:
      [
        './daprd',
        '-app-id',
        'fetch-api',
        '-app-port',
        '80',
        '-components-path',
        '/components',
        '-config',
        '/configuration/eprocessor-config.yaml',
      ]
    volumes:
      - './dapr/components/:/components'
      - './dapr/configuration/:/configuration'

  process-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - SeqServerUrl=http://seq
    ports:
      - '5161:80'
      - '50161:50160'

  process-api-dapr:
    command:
      [
        './daprd',
        '-app-id',
        'process-api',
        '-app-port',
        '80',
        '-components-path',
        '/components',
        '-config',
        '/configuration/eprocessor-config.yaml',
      ]
    volumes:
      - './dapr/components/:/components'
      - './dapr/configuration/:/configuration'

  send-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - SeqServerUrl=http://seq
    ports:
      - '5163:80'
      - '50163:50162'

  send-api-dapr:
    command:
      [
        './daprd',
        '-app-id',
        'send-api',
        '-app-port',
        '80',
        '-components-path',
        '/components',
        '-config',
        '/configuration/eprocessor-config.yaml',
      ]
    volumes:
      - './dapr/components/:/components'
      - './dapr/configuration/:/configuration'

  webstatus:
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HealthChecksUI__HealthChecks__1__Name=FakeFetch CA API
      - HealthChecksUI__HealthChecks__1__Uri=http://fake-fetch-ca-api/hc
      - HealthChecksUI__HealthChecks__2__Name=Process API
      - HealthChecksUI__HealthChecks__2__Uri=http://process-api/hc
      - HealthChecksUI__HealthChecks__3__Name=Send API
      - HealthChecksUI__HealthChecks__3__Uri=http://send-api/hc

    ports:
      - '5107:80'

  dapr-placement:
    command: ['./placement', '-port', '50000', '-log-level', 'debug']
    ports:
      - '50000:50000'

volumes:
  eprocessor-sqldata:
    external: false
