// <auto-generated />
using System;
using Ecmanage.eProcessor.Services.Process.Process.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Process.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecmanage.eProcessor.Services.Process.Process.Domain.Entities.EmailQueueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmailQueueId")
                        .HasColumnType("int");

                    b.Property<int>("EmailTemplateId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SendAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sent")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("XslName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmailTemplateId")
                        .IsUnique();

                    b.ToTable("EmailQueueItem", (string)null);
                });

            modelBuilder.Entity("Ecmanage.eProcessor.Services.Process.Process.Domain.Entities.EmailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("EmailTemplate");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Ecmanage.eProcessor.Services.Process.Process.Domain.Entities.EmailTemplates.Login", b =>
                {
                    b.HasBaseType("Ecmanage.eProcessor.Services.Process.Process.Domain.Entities.EmailTemplate");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Login", (string)null);
                });

            modelBuilder.Entity("Ecmanage.eProcessor.Services.Process.Process.Domain.Entities.EmailTemplates.Overdue", b =>
                {
                    b.HasBaseType("Ecmanage.eProcessor.Services.Process.Process.Domain.Entities.EmailTemplate");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverdueDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Overdue", (string)null);
                });

            modelBuilder.Entity("Ecmanage.eProcessor.Services.Process.Process.Domain.Entities.EmailTemplates.Report", b =>
                {
                    b.HasBaseType("Ecmanage.eProcessor.Services.Process.Process.Domain.Entities.EmailTemplate");

                    b.Property<string>("PortalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Report", (string)null);
                });

            modelBuilder.Entity("Ecmanage.eProcessor.Services.Process.Process.Domain.Entities.EmailTemplates.User", b =>
                {
                    b.HasBaseType("Ecmanage.eProcessor.Services.Process.Process.Domain.Entities.EmailTemplate");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageHeader")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Ecmanage.eProcessor.Services.Process.Process.Domain.Entities.EmailQueueItem", b =>
                {
                    b.HasOne("Ecmanage.eProcessor.Services.Process.Process.Domain.Entities.EmailTemplate", "EmailTemplate")
                        .WithOne("EmailQueueItem")
                        .HasForeignKey("Ecmanage.eProcessor.Services.Process.Process.Domain.Entities.EmailQueueItem", "EmailTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmailTemplate");
                });

            modelBuilder.Entity("Ecmanage.eProcessor.Services.Process.Process.Domain.Entities.EmailTemplates.Login", b =>
                {
                    b.HasOne("Ecmanage.eProcessor.Services.Process.Process.Domain.Entities.EmailTemplate", null)
                        .WithOne()
                        .HasForeignKey("Ecmanage.eProcessor.Services.Process.Process.Domain.Entities.EmailTemplates.Login", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ecmanage.eProcessor.Services.Process.Process.Domain.Entities.EmailTemplates.Overdue", b =>
                {
                    b.HasOne("Ecmanage.eProcessor.Services.Process.Process.Domain.Entities.EmailTemplate", null)
                        .WithOne()
                        .HasForeignKey("Ecmanage.eProcessor.Services.Process.Process.Domain.Entities.EmailTemplates.Overdue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ecmanage.eProcessor.Services.Process.Process.Domain.Entities.EmailTemplates.Report", b =>
                {
                    b.HasOne("Ecmanage.eProcessor.Services.Process.Process.Domain.Entities.EmailTemplate", null)
                        .WithOne()
                        .HasForeignKey("Ecmanage.eProcessor.Services.Process.Process.Domain.Entities.EmailTemplates.Report", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ecmanage.eProcessor.Services.Process.Process.Domain.Entities.EmailTemplates.User", b =>
                {
                    b.HasOne("Ecmanage.eProcessor.Services.Process.Process.Domain.Entities.EmailTemplate", null)
                        .WithOne()
                        .HasForeignKey("Ecmanage.eProcessor.Services.Process.Process.Domain.Entities.EmailTemplates.User", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ecmanage.eProcessor.Services.Process.Process.Domain.Entities.EmailTemplate", b =>
                {
                    b.Navigation("EmailQueueItem")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
